---

services:
  foundry:
    build: .
    hostname: battle_transitions
    env_file: ".env"
    # volumes:
    #   - type: bind
    #     source: ./FoundryData
    #     target: /data
    ports:
      - target: 30000
        published: 30000
        protocol: tcp