---

services:
  foundry:
    build: .
    hostname: battle_transitions
    env_file: ".env"
    volumes:
      - type: bind
        source: ./dist
        target: /data/Data/modules/battle-transitions
        read_only: true
      # - ./dist:/data/Data/modules/battle-transitions
    ports:
      - target: 30000
        published: 30000
        protocol: tcp